"""empty message

Revision ID: 2692aa044b44
Revises: 7a7aef0133da
Create Date: 2022-03-18 14:52:56.412073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2692aa044b44'
down_revision = '7a7aef0133da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('imgsrc', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'imgsrc')
    # ### end Alembic commands ###
