"""empty message

Revision ID: 3fd3f1585ed8
Revises: 2692aa044b44
Create Date: 2022-03-18 15:15:48.202177

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3fd3f1585ed8'
down_revision = '2692aa044b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kampaniyalar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('describtion', sa.String(length=255), nullable=True),
    sa.Column('imgsrc', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('card', 'imgsrc',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'imgsrc',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_table('kampaniyalar')
    # ### end Alembic commands ###
