"""empty message

Revision ID: 4e2d131ac8ce
Revises: 3fd3f1585ed8
Create Date: 2022-03-18 15:44:34.866080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e2d131ac8ce'
down_revision = '3fd3f1585ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kampaniyalar', sa.Column('description', sa.String(length=255), nullable=True))
    op.drop_column('kampaniyalar', 'describtion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kampaniyalar', sa.Column('describtion', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('kampaniyalar', 'description')
    # ### end Alembic commands ###
