"""empty message

Revision ID: aa3dff1683f9
Revises: 4e2d131ac8ce
Create Date: 2022-03-18 22:12:11.421944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3dff1683f9'
down_revision = '4e2d131ac8ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kampaniyalar', sa.Column('category', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kampaniyalar', 'category')
    # ### end Alembic commands ###
