"""empty message

Revision ID: b71a806bec0a
Revises: 22bcc4a4422d
Create Date: 2022-03-29 12:56:34.403453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b71a806bec0a'
down_revision = '22bcc4a4422d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cancellation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('till30_1', sa.String(length=100), nullable=True),
    sa.Column('till30_2', sa.String(length=100), nullable=True),
    sa.Column('till30_3', sa.String(length=100), nullable=True),
    sa.Column('till180_1', sa.String(length=100), nullable=True),
    sa.Column('till180_2', sa.String(length=100), nullable=True),
    sa.Column('till180_3', sa.String(length=100), nullable=True),
    sa.Column('till360_1', sa.String(length=100), nullable=True),
    sa.Column('till360_2', sa.String(length=100), nullable=True),
    sa.Column('till360_3', sa.String(length=100), nullable=True),
    sa.Column('after360_1', sa.String(length=100), nullable=True),
    sa.Column('after360_2', sa.String(length=100), nullable=True),
    sa.Column('after360_3', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_frequency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teleb1', sa.String(length=100), nullable=True),
    sa.Column('teleb2', sa.String(length=100), nullable=True),
    sa.Column('teleb3', sa.String(length=100), nullable=True),
    sa.Column('threemonth1', sa.String(length=100), nullable=True),
    sa.Column('threemonth2', sa.String(length=100), nullable=True),
    sa.Column('threemonth3', sa.String(length=100), nullable=True),
    sa.Column('sixmonth1', sa.String(length=100), nullable=True),
    sa.Column('sixmonth2', sa.String(length=100), nullable=True),
    sa.Column('sixmonth3', sa.String(length=100), nullable=True),
    sa.Column('twelvemonth1', sa.String(length=100), nullable=True),
    sa.Column('twelvemonth2', sa.String(length=100), nullable=True),
    sa.Column('twelvemonth3', sa.String(length=100), nullable=True),
    sa.Column('twenty4month1', sa.String(length=100), nullable=True),
    sa.Column('twenty4month2', sa.String(length=100), nullable=True),
    sa.Column('twenty4month3', sa.String(length=100), nullable=True),
    sa.Column('thirty6month1', sa.String(length=100), nullable=True),
    sa.Column('thirty6month2', sa.String(length=100), nullable=True),
    sa.Column('thirty6month3', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_frequency')
    op.drop_table('cancellation')
    # ### end Alembic commands ###
